# test workflow template
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # generateName: <project-name>-
  generateName: project-name-
  namespace: argo-workspace
spec:
  workflowTemplateRef:
    name: workflow-template-build-template
  arguments:
    parameters: 
      - name: revision
        value: master



        